sudo: false

language: python

python:
  - 2.7

before_install: cd tests

install:
  - pip install -r ../requirements.txt
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov